repos:
  - repo: local
    hooks:
      - id: update-readme
        name: Update README with charts
        entry: python .github/scripts/update-readme.py
        language: python
        files: ^charts/.*/Chart\.yaml$
        always_run: true
        pass_filenames: false 