apiVersion: v2
kubeVersion: ">=1.23.0-0"
icon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/icon.png
type: application
name: homepage
home: https://gethomepage.dev/
description: A Helm chart for Homepage - A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations.
version: 1.3.20
appVersion: "v1.4.0"
sources:
  - https://github.com/gethomepage/homepage
keywords:
  - homepage
  - dashboard
  - startpage
  - kubernetes
maintainers:
  - name: MoonLab
    url: https://github.com/moonlab-tech
