# Alternative: Direct Cross-Namespace PVC Reference
# This works in newer Kubernetes versions (1.26+)

---
# Step 1: Create the original PVC in shared namespace
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: shared-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-storage

---
# Step 2: Radarr deployment with direct PVC reference
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr  # ← Different namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: ghcr.io/home-operations/radarr:latest
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: media-storage
          mountPath: /media
        - name: config
          mountPath: /config
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-storage
          namespace: shared-storage  # ← Direct reference to PVC in different namespace
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config

---
# Step 3: Jellyfin deployment with direct PVC reference
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin  # ← Different namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: media-storage
          mountPath: /media
        - name: config
          mountPath: /config
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-storage
          namespace: shared-storage  # ← Direct reference to PVC in different namespace
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config 