# Example values file for deployment restart permissions
# This allows Homepage to restart deployments (including itself)

rbac:
  create: true
  # Additional rules for deployment restart functionality
  additionalRules:
    # Allow restarting deployments
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "patch", "update"]
    - apiGroups: ["apps"]
      resources: ["deployments/restart"]
      verbs: ["patch"]
    # Allow viewing events for monitoring
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["get", "list", "watch"]

# Example configuration for Homepage to use restart functionality
config:
  services: |
    - System Management:
        - Restart Homepage:
            href: /api/kubernetes/apps/v1/deployments/homepage/restart
            description: Restart the Homepage deployment
            icon: refresh.png
        - View Events:
            href: /api/kubernetes/v1/events
            description: View cluster events
            icon: events.png

  widgets: |
    - kubernetes:
        deployments:
          show: true
          showLabel: true
          label: "deployments"
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default 