# Example values file for enhanced RBAC permissions
# This allows Homepage to restart deployments and manage other resources

rbac:
  create: true
  # Additional rules for deployment management and monitoring
  additionalRules:
    # Allow restarting deployments
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "patch", "update"]
    - apiGroups: ["apps"]
      resources: ["deployments/restart"]
      verbs: ["patch"]
    # Allow managing replicasets
    - apiGroups: ["apps"]
      resources: ["replicasets"]
      verbs: ["get", "list"]
    # Allow viewing events for better monitoring
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["get", "list", "watch"]
    # Allow managing services
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list", "patch", "update"]
    # Allow managing configmaps for dynamic configuration
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "patch", "update"]
    # Allow managing secrets (be careful with this permission)
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "list"]
    # Allow managing persistent volume claims
    - apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "patch", "update"]
    # Allow managing jobs and cronjobs
    - apiGroups: ["batch"]
      resources: ["jobs", "cronjobs"]
      verbs: ["get", "list", "patch", "update", "delete"]

# Example configuration for Homepage to use these permissions
config:
  services: |
    - Cluster Management:
        - Restart Homepage:
            href: /api/kubernetes/apps/v1/deployments/homepage/restart
            description: Restart the Homepage deployment
            icon: refresh.png
        - View Events:
            href: /api/kubernetes/v1/events
            description: View cluster events
            icon: events.png
        - Manage Services:
            href: /api/kubernetes/v1/services
            description: Manage Kubernetes services
            icon: services.png

  widgets: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
        deployments:
          show: true
          showLabel: true
          label: "deployments"
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank

# Enable ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: homepage.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: homepage-tls
      hosts:
        - homepage.example.com 