{{- if and .Values.rbac.create (not .Values.rbac.existingClusterRoleBinding) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homepage.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "homepage.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
