{{- if and (not (include "homepage.shouldCreateConfigMap" .)) (not (index .Values.config.existingConfigMaps "widgets")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-widgets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  widgets.yaml: |
{{ .Values.config.widgets | indent 4 }}
{{- end }} 