{{- if eq (include "homepage.shouldCreateConfigMap" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  kubernetes.yaml: |
{{ .Values.config.kubernetes | indent 4 }}
  settings.yaml: |
{{ .Values.config.settings | indent 4 }}
  custom.css: |
{{ .Values.config.customCss | indent 4 }}
  custom.js: |
{{ .Values.config.customJs | indent 4 }}
  bookmarks.yaml: |
{{ .Values.config.bookmarks | indent 4 }}
  services.yaml: |
{{ .Values.config.services | indent 4 }}
  widgets.yaml: |
{{ .Values.config.widgets | indent 4 }}
  docker.yaml: {{ .Values.config.docker | quote }}
{{- end }}
