{{- if and (not (include "homepage.shouldCreateConfigMap" .)) (not (index .Values.config.existingConfigMaps "kubernetes")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  kubernetes.yaml: |
{{ .Values.config.kubernetes | indent 4 }}
{{- end }} 