{{- if and (not (include "homepage.shouldCreateConfigMap" .)) (not (index .Values.config.existingConfigMaps "services")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  services.yaml: |
{{ .Values.config.services | indent 4 }}
{{- end }} 