{{- if eq (include "homepage.shouldCreateConfigMap" .) "true" }}
# Individual ConfigMaps for each configuration file
{{- if not (index .Values.config.existingConfigMaps "kubernetes") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  kubernetes.yaml: |
{{ .Values.config.kubernetes | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "settings") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  settings.yaml: |
{{ .Values.config.settings | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "bookmarks") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-bookmarks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  bookmarks.yaml: |
{{ .Values.config.bookmarks | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "services") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  services.yaml: |
{{ .Values.config.services | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "widgets") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-widgets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  widgets.yaml: |
{{ .Values.config.widgets | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "docker") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-docker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  docker.yaml: |
{{ .Values.config.docker | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "customCss") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-customcss
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  custom.css: |
{{ .Values.config.customCss | indent 4 }}
{{- end }}

{{- if not (index .Values.config.existingConfigMaps "customJs") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-customjs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  custom.js: |
{{ .Values.config.customJs | indent 4 }}
{{- end }}
{{- end }} 
