{{- if and (not (include "homepage.shouldCreateConfigMap" .)) (not (index .Values.config.existingConfigMaps "customCss")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-customcss
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  custom.css: |
{{ .Values.config.customCss | indent 4 }}
{{- end }} 