apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homepage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "homepage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homepage.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "homepage.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: config-customjs
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: config-customcss
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: config-bookmarks
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: config-docker
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: config-kubernetes
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: config-services
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: config-settings
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: config-widgets
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-kubernetes
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "kubernetes") }}
        - name: config-settings
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "settings") }}
        - name: config-bookmarks
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "bookmarks") }}
        - name: config-services
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "services") }}
        - name: config-widgets
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "widgets") }}
        - name: config-docker
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "docker") }}
        - name: config-customcss
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "customCss") }}
        - name: config-customjs
          configMap:
            name: {{ include "homepage.configMapNameForFile" (dict "context" . "file" "customJs") }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "homepage.fullname" . }}-logs
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
